<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>greetings</name>
  <uuid>0d8a3d7d-122c-4d13-8d44-6512e0afdb61</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[if
    the name of request is "hector"
then
    set decision to a new BREResponse where
        the mesage is "Good morning "  + the name of request ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
