<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>test git</name>
  <uuid>b720bcf2-46f0-45a5-84f1-943f9f9d2da7</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set the disease of decision to ALLERGIES ; 
]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
